In [47]:
def display(title, img):
    cv2.imshow(title, img)
    # Chờ một khoảng thời gian
    cv2.waitKey(0)
    # Đóng window
    cv2.destroyWindow(title)

In [48]:
import cv2
import numpy as np 

In [49]:
path= 'C:/Users/dinhl/Pictures/picture/1.jpg'
img = cv2.imread(path)
print(img)

[[[179 164  41]
  [179 164  41]
  [180 165  42]
  ...
  [176 165  44]
  [178 165  43]
  [177 164  42]]

 [[180 165  42]
  [179 164  41]
  [180 165  42]
  ...
  [176 165  44]
  [178 165  43]
  [178 165  43]]

 [[180 165  42]
  [180 165  42]
  [180 165  42]
  ...
  [177 166  44]
  [177 166  44]
  [177 166  44]]

 ...

 [[ 54  26   9]
  [ 54  26   9]
  [ 54  26   9]
  ...
  [ 54  26   9]
  [ 53  25   8]
  [ 53  25   8]]

 [[ 54  26   9]
  [ 54  26   9]
  [ 54  26   9]
  ...
  [ 54  26   9]
  [ 56  26   9]
  [ 55  25   8]]

 [[ 54  26   9]
  [ 54  26   9]
  [ 54  26   9]
  ...
  [ 54  26   9]
  [ 56  26   9]
  [ 56  26   9]]]


In [50]:
# Lấy kích thước
print(img.shape)
x, y, z = img.shape
print(x)
print(y)
print(z)

(1280, 1920, 3)
1280
1920
3


In [51]:
cv2.imshow('Window', img)
# Chờ một khoảng thời gian
cv2.waitKey(10000)
# Đóng window
cv2.destroyWindow('Window')

In [52]:
b, g, r = cv2.split(img)
cv2.imshow('Window', img)
cv2.imshow('Red', r)
cv2.imshow('Green', g)
cv2.imshow('Blue', b)

# Chờ một khoảng thời gian
cv2.waitKey(0)
# Đóng window
cv2.destroyAllWindows()


In [53]:
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_2 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.imshow('Window', img)
cv2.imshow('gray_img', gray_img)
cv2.imshow('img_2', img_2)
# Chờ một khoảng thời gian
cv2.waitKey(0)
# Đóng window
cv2.destroyAllWindows()