In [2]:
import numpy as np

a = np.array([1,2,3])

print(a)

element = a[1]
print(element)

[1 2 3]
2


In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)

element = matrix[1, 2]
print(element)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [4]:
a = np.zeros(5)
print(a)

a = np.ones(5)
print(a)

a = np.empty(5)
print(a)

a = np.arange(100)
print(a)

a = np.linspace(0, 10, num=5)
print(a)

a = np.ones(5, dtype=np.int64)
a

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.   2.5  5.   7.5 10. ]


array([1, 1, 1, 1, 1])

In [5]:
arr = np.array([3, 1, 2, 4, 5])
print(arr)

arr = np.sort(arr)
print(arr)

arr = np.sort(arr)[::-1]
print(arr)

arr = np.append(arr, 100)
print(arr)

arr = np.delete(arr, 3)
print(arr)

[3 1 2 4 5]
[1 2 3 4 5]
[5 4 3 2 1]
[  5   4   3   2   1 100]
[  5   4   3   1 100]


In [6]:
arr = np.array([[3, 1, 2],
                [4, 6, 8],
                [9, 7, 5]])

sap_xep_theo_hang = np.sort(arr, axis=1) # tăng dần
print(sap_xep_theo_hang)

sap_xep_theo_cot = np.sort(arr, axis=0) # tăng dần
print(sap_xep_theo_cot)

[[1 2 3]
 [4 6 8]
 [5 7 9]]
[[3 1 2]
 [4 6 5]
 [9 7 8]]


In [ ]:
arr = np.array([[3, 1, 2],
                [4, 6, 8],
                [9, 7, 5]])

sap_xep_theo_hang = -np.sort(-arr, axis=1)
print(sap_xep_theo_hang)

sap_xep_theo_cot = -np.sort(-arr, axis=0) 
print(sap_xep_theo_cot)

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

so_chieu = arr.ndim  
kich_thuoc = arr.size  
hinh_dang = arr.shape

print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)

Số chiều: 2
Kích thước: 6
Hình dạng: (2, 3)


In [7]:
import numpy as np

arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

so_chieu = arr_3d.ndim  
kich_thuoc = arr_3d.size  
hinh_dang = arr_3d.shape

print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)

Số chiều: 3
Kích thước: 12
Hình dạng: (2, 2, 3)


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(float)
print(arr_float)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

In [ ]:
reshaped_arr = reshaped_arr.flatten() # Chuyển thành mảng 1 chiều
print(reshaped_arr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

sub_arr = arr[1:4]  # Cắt từ phần tử thứ 1 đến 4
print(sub_arr) # 2 3 4 5

sub_arr = arr[:-1]  # 1 2 3 4
print(sub_arr)

sub_arr = arr[-2:]  # 4 5 
print(sub_arr)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

transposed_arr = arr.T
print(transposed_arr)

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

In [9]:
arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)
print("Tổng của mảng arr:", total)

average = np.mean(arr)
print("Giá trị trung bình của mảng arr:", average)

max_value = np.max(arr)
min_value = np.min(arr)
print("Giá trị lớn nhất trong mảng arr:", max_value)
print("Giá trị nhỏ nhất trong mảng arr:", min_value)

std_deviation = np.std(arr)
print("Độ lệch chuẩn của mảng arr:", std_deviation)

variance = np.var(arr)
print("Phương sai của mảng arr:", variance)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print("Tổng tích chập của arr1 và arr2:", dot_product)

Tổng của mảng arr: 15
Giá trị trung bình của mảng arr: 3.0
Giá trị lớn nhất trong mảng arr: 5
Giá trị nhỏ nhất trong mảng arr: 1
Độ lệch chuẩn của mảng arr: 1.4142135623730951
Phương sai của mảng arr: 2.0
Tổng tích chập của arr1 và arr2: 32


In [10]:
import numpy as np

def calculate_sum(arr):
    return np.sum(arr)

def calculate_mean(arr):
    return np.mean(arr)

def calculate_min_max(arr):
    max_value = np.max(arr)
    min_value = np.min(arr)
    max_index = np.argmax(arr)
    min_index = np.argmin(arr)
    return max_value, min_value, max_index, min_index

def calculate_std_var(arr):
    std_deviation = np.std(arr)
    variance = np.var(arr)
    return std_deviation, variance

def calculate_dot_product(arr1, arr2):
    if arr1.shape != arr2.shape:
        raise ValueError("Hai mảng phải có cùng kích thước để tính tích chập.")
    return np.dot(arr1, arr2)

def calculate_median(arr):
    return np.median(arr)

def process_array(arr):
    print(f"Mảng: {arr}")
    print(f"Tổng của mảng: {calculate_sum(arr)}")
    print(f"Giá trị trung bình: {calculate_mean(arr)}")
    print(f"Giá trị trung vị: {calculate_median(arr)}")
    
    max_value, min_value, max_index, min_index = calculate_min_max(arr)
    print(f"Giá trị lớn nhất: {max_value} tại vị trí {max_index}")
    print(f"Giá trị nhỏ nhất: {min_value} tại vị trí {min_index}")
    
    std_deviation, variance = calculate_std_var(arr)
    print(f"Độ lệch chuẩn: {std_deviation}")
    print(f"Phương sai: {variance}")

arr = np.array([1, 2, 3, 4, 5])
process_array(arr)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(f"Tổng tích chập của arr1 và arr2: {calculate_dot_product(arr1, arr2)}")

Mảng: [1 2 3 4 5]
Tổng của mảng: 15
Giá trị trung bình: 3.0
Giá trị trung vị: 3.0
Giá trị lớn nhất: 5 tại vị trí 4
Giá trị nhỏ nhất: 1 tại vị trí 0
Độ lệch chuẩn: 1.4142135623730951
Phương sai: 2.0
Tổng tích chập của arr1 và arr2: 32
